### ISSUE TITLE
TypeError: invalid extended field value,when parse the filename 

### ISSUE THREAD

**Issue by cobola** [kevva/download#145]
TypeError: invalid extended field value

http://77fyok.com1.z0.glb.clouddn.com/avatar.jpg

the example url

**Comment by ZhaZhengRefn** [comment]
have the same problem.

**Comment by PandaTsui** [comment]
me too.

**Comment by kevva** [comment]
Can you provide a code example?

**Comment by ZengTianShengZ** [comment]
i have the same problem, here the code example

```
download('https://cdn.dancf.com/assets/place.png', 'dist/cdn')
    .then(res => {
        console.log(res);
    })
    .catch(err => {
        console.log(err);
    });
```

the error log:
```
TypeError: invalid extended field value
    at decodefield (xxxx/node_modules/content-disposition/index.js:269:11)
    at Function.parse (xxxx/node_modules/content-disposition/index.js:358:15)
    at getFilename (xxxx/node_modules/download/index.js:41:37)
    at pEvent.then.then.result (xxxxxx/node_modules/download/index.js:84:48)
```
