### ISSUE TITLE
install using npm 

### ISSUE THREAD

**Issue by salahaldin** [kevva/download#152]
Hello May  be this is not related to the library itself , but when I try to download it using npm i get an error

` npm install download

> gifsicle@3.0.4 postinstall /path/node_modules/gifsicle
> node lib/install.js

url.js:103
    throw new TypeError('Parameter "url" must be a string, not ' + typeof url);
    ^

TypeError: Parameter "url" must be a string, not object
    at Url.parse (url.js:103:11)
    at Object.urlParse [as parse] (url.js:97:13)
    at module.exports (/path/node_modules/download/index.js:66:21)
    at BinWrapper.download (/path/node_modules/bin-wrapper/index.js:200:31)
    at BinWrapper.<anonymous> (/path/node_modules/bin-wrapper/index.js:178:9)
    at FSReqWrap.oncomplete (fs.js:152:21)

> jpegtran-bin@3.2.0 postinstall /path/node_modules/jpegtran-bin
> node lib/install.js

url.js:103
    throw new TypeError('Parameter "url" must be a string, not ' + typeof url);
    ^

TypeError: Parameter "url" must be a string, not object
    at Url.parse (url.js:103:11)
    at Object.urlParse [as parse] (url.js:97:13)
    at module.exports (/path/node_modules/download/index.js:66:21)
    at BinWrapper.download (/path/node_modules/bin-wrapper/index.js:200:31)
    at BinWrapper.<anonymous> (/path/node_modules/bin-wrapper/index.js:178:9)
    at FSReqWrap.oncomplete (fs.js:152:21)

> optipng-bin@3.1.4 postinstall /path/node_modules/optipng-bin
> node lib/install.js

url.js:103
    throw new TypeError('Parameter "url" must be a string, not ' + typeof url);
    ^

TypeError: Parameter "url" must be a string, not object
    at Url.parse (url.js:103:11)
    at Object.urlParse [as parse] (url.js:97:13)
    at module.exports (/path/node_modules/download/index.js:66:21)
    at BinWrapper.download (/path/node_modules/bin-wrapper/index.js:200:31)
    at BinWrapper.<anonymous> (/path/node_modules/bin-wrapper/index.js:178:9)
    at FSReqWrap.oncomplete (fs.js:152:21)
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: gifsicle@3.0.4 (node_modules/gifsicle):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: gifsicle@3.0.4 postinstall: `node lib/install.js`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: jpegtran-bin@3.2.0 (node_modules/jpegtran-bin):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: jpegtran-bin@3.2.0 postinstall: `node lib/install.js`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: optipng-bin@3.1.4 (node_modules/optipng-bin):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: optipng-bin@3.1.4 postinstall: `node lib/install.js`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

+ download@6.2.5
updated 1 package in 12.684s`

The node version is : 8.9.4
npm version : 5.6.0

**Comment by salahaldin** [comment]
After a better look, it is clear the issue is related to gifsicle. Thanks any way
